import { Restaurant } from './types';

export const restaurantData: Restaurant[] = [
  {
    id: 1,
    name: "Wingo's",
    cuisine: ["american", "appetizers", "comfort food"],
    address: "Glover Park – 2301 Wisconsin Ave NW",
    nearestUniversity: "Georgetown University",
    acceptsCampusCard: true,
    distance: "0.2 miles",
    rating: 4.2,
    menuItems: [
      {
        name: "BAKED MAC & CHEESE",
        price: 3.99,
        description: "Traditional mac and cheese topped with smoked cheddar and scallions",
        imageUrl: "https://i.imgur.com/ef7LQKZ.png"
      },
      {
        name: "BUTTERFLY SHRIMP",
        price: 8.99,
        description: "8 pcs served with cocktail sauce",
        imageUrl: "https://i.imgur.com/wlJ57Fc.png"
      },
      { name: "CORN ON THE COB", price: 3.99, description: "Grilled with salt, butter, and cilantro", imageUrl: "https://i.imgur.com/LvtykaP.png" },
      { name: "DEEP-FRIED MAC & CHEESE", price: 5.99, description: "8 pcs", imageUrl: "https://i.imgur.com/BzYcKZx.png" },
      { name: "LARGE FRIES", price: 9.99, description: "Your choice of seasoned or plain, then add your favorite toppings", imageUrl: "https://i.imgur.com/NKPz1WE.png" },
      { name: "MEDIUM FRIES", price: 6.99, description: "Your choice of seasoned or plain, then add your favorite toppings", imageUrl: "https://i.imgur.com/NKPz1WE.png" },
      { name: "SMALL FRIES", price: 4.99, description: "Your choice of seasoned or plain, then add your favorite toppings", imageUrl: "https://i.imgur.com/NKPz1WE.png" },
      { name: "FRESH FRIED MOZZARELLA", price: 6.99, description: "Mozzarella cheese, battered and fried, sprinkled with basil", imageUrl: "https://i.imgur.com/uWgVpeA.png" },
      { name: "FRIED CHEESE RAVIOLI", price: 6.99, description: "8 pieces of cheese ravioli, battered and fried to perfection", imageUrl: "https://i.imgur.com/AK4u9Ps.png" },
      { name: "JALAPENO POPPERS", price: 6.99, description: "6 pcs Jalapeno peppers stuffed with cream cheese", imageUrl: "https://i.imgur.com/pyDEATy.png" },
      { name: "JUMBO BAVARIAN PRETZEL", price: 6.99, description: "", imageUrl: "https://i.imgur.com/xqfjpwD.png" },
      { name: "MASHED POTATOES & GRAVY", price: 3.99, description: "Fresh Idaho potatoes puree topped with scallions, a hint of kosher salt and Malsabar black peppercorns", imageUrl: "https://i.imgur.com/mzbECbs.png" },
      { name: "MINI CORN DOGS", price: 6.99, description: "8 pieces of beef dogs wrapped in dough and fried. served with bbq dip", imageUrl: "https://i.imgur.com/4ZqIyQC.png" },
      { name: "MOZZARELLA STICKS", price: 6.99, description: "8 pieces served with marinara", imageUrl: "https://i.imgur.com/uWgVpeA.png" },
      { name: "ONION RINGS", price: 5.99, description: "8 hand sliced & battered onion rings, fried to perfection", imageUrl: "https://i.imgur.com/N7Drj4T.png" },
      { name: "POTATO SKINS", price: 6.99, description: "With bacon, sour cream, scallions, and cheddar", imageUrl: "https://i.imgur.com/Ygs9J9U.png" },
      { name: "SEASONED FRIES SMALL", price: 4.99, description: "", imageUrl: "https://i.imgur.com/NKPz1WE.png" },
      { name: "SEASONED FRIES LARGE", price: 9.99, description: "", imageUrl: "https://i.imgur.com/NKPz1WE.png" },
      { name: "SEASONED FRIES MEDIUM", price: 6.99, description: "", imageUrl: "https://i.imgur.com/NKPz1WE.png" },
      { name: "STEAK & CHEESE POPPERS", price: 6.99, description: "(3 pcs) Straight From the Bronx, Steak, onions and cheddar", imageUrl: "https://i.imgur.com/hKpEcws.png" },
      { name: "MISS VICKIES POTATO CHIPS", price: 1.49, description: "", imageUrl: "https://i.imgur.com/SKcNQUL.png" }
    ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: false,
      inhouse: true
    }
  },
  {
    id: 2,
    name: "Angelico Pizzeria",
    cuisine: ["pizza", "italian", "comfort food"],
    address: "3205 Mt Pleasant St NW, Washington, DC 20010",
    nearestUniversity: "American University",
    acceptsCampusCard: true,
    distance: "3.2 miles",
    rating: 4.9,
    menuItems: [
        { name: "Margherita Pizza", price: 17.99, description: "Light tomato sauce, fresh mozzarella, basil & tomatoes drizzled with olive oil." },
        { name: "Chicken Pesto Pizza", price: 17.99, description: "Pesto sauce, mozzarella, grilled chicken breast, sun-dried tomatoes, roasted red peppers, red onions, kalamata olives & feta." },
        { name: "Supremo Pizza", price: 17.99, description: "Tomato sauce, mozzarella, pepperoni, mushrooms, green peppers, caramelized onions, Italian sausage & black olives." },
        { name: "Meat Classic Pizza", price: 17.99, description: "Tomato sauce, mozzarella, pepperoni, bacon, ham & Italian sausage." },
        { name: "Spicy Chicken Pizza", price: 17.99, description: "Spicy roasted red pepper sauce, mozzarella, grilled chicken, mushrooms, sun-dried tomatoes & red onions." },
        { name: "Spinach & Artichoke Pizza", price: 17.99, description: "Garlic herb sauce, mozzarella, tomatoes, mushrooms, caramelized onions, baby spinach, artichokes & feta." },
        { name: "Asiago Bacon Chicken Pizza", price: 17.99, description: "Asiago, bacon & chicken with mozzarella, caramelized onions, tomatoes, basil & olive oil sauce." },
        { name: "Roasted Eggplant Pizza", price: 17.99, description: "Garlic herb sauce, mozzarella, eggplant, sun-dried tomatoes, roasted red peppers, kalamata olives, feta & roasted garlic." },
        { name: "Angelico Special Pizza", price: 17.99, description: "Tomato sauce, mozzarella, pepperoni, Italian sausage, ham, caramelized onions & roasted red peppers." },
        { name: "Vegetariano Pizza", price: 17.99, description: "Tomato sauce, mozzarella, tomatoes, mushrooms, green peppers, red onions & black olives." },
        { name: "Portobello Mushroom Pizza", price: 17.99, description: "Garlic herb sauce, mozzarella, portobello mushrooms, roasted red peppers, baby spinach & feta." },
        { name: "Sicilian Pizza", price: 17.99, description: "Light tomato sauce, prosciutto, fresh mozzarella, roasted red peppers, kalamata olives, drizzled with olive oil." },
        { name: "Pizza Prosciutto", price: 17.99, description: "Fresh mozzarella, prosciutto, caramelized onions, baby spinach & olive oil sauce." },
        { name: "Cheesesteak Asiago Pizza", price: 17.99, description: "Alfredo sauce, Asiago mozzarella, peppers, caramelized onions & sliced steak." }
        ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
  {
    id: 3,
    name: "Bandit Taco Tenleytown",
    cuisine: ["mexican", "appetizers", "tacos"],
    address: "4629 41st St NW, Washington, DC 20016",
    nearestUniversity: "American University",
    acceptsCampusCard: true,
    distance: "0.9 miles",
    rating: 4.2,
    menuItems: [

            { name: "Refried Beans and Egg Taco", price: 3.75, description: "Flour tortilla, scrambled eggs, mozzarella cheese, refried beans and poblano sauce. (Add protein +$0.75)" },
            { name: "Crispy Chicken and Egg Taco", price: 4.25, description: "Flour tortilla, scrambled eggs, fried chicken, mozzarella cheese and chipotle sauce." },
            { name: "Steak and Egg Taco", price: 4.50, description: "Flour tortilla, scrambled eggs, steak, mozzarella cheese, chipotle sauce and potatoes." },
            { name: "Bacon and Egg Taco", price: 3.75, description: "Flour tortilla, scrambled eggs, bacon, mozzarella cheese. (Add protein +$0.75)" },
            { name: "Breakfast Torta", price: 10.00, description: "Bread, scrambled eggs, mozzarella cheese, bean spread, guac spread and poblano sauce. (Add protein +$1.50-$2.25)" },
            { name: "Breakfast Burrito", price: 10.00, description: "Mozzarella cheese, potatoes, refried beans, scrambled eggs and poblano sauce. (Add protein +$1.50-$2.25)" },
            { name: "Breakfast Quesadilla", price: 10.00, description: "Scrambled eggs, refried beans, bacon, mozzarella cheese, and chipotle sauce. (Add protein +$1.50-$2.25)" },
          
            // Tacos Menu Items
            { name: "Skirt Steak Taco", price: 4.35, description: "Onions, scallions, cilantro and radishes on a corn tortilla." },
            { name: "Adobo Chicken Taco", price: 3.85, description: "Onions, scallions, cilantro and radishes on a corn tortilla." },
            { name: "Al Pastor Taco", price: 4.60, description: "Onions, scallions, cilantro, radishes and pineapple on a corn tortilla." },
            { name: "Crispy Shrimp Taco", price: 4.60, description: "Onions, scallions, cilantro, cabbage, radishes, salsa verde and lemon sake on a corn tortilla. Choose up to 3 sauces: Salsa Verde, Salsa Roja, Habanero." },
            { name: "Tofu Taco", price: 4.35, description: "Corn and mixed peppers, cilantro, scallions, and poblano sauce on corn tortilla." },
            { name: "Barbacoa Taco", price: 4.35, description: "Spicy beef with onions, cilantro and radishes." },
            { name: "Chorizo Taco", price: 3.85, description: "Onions, scallions, cilantro and radishes on a corn tortilla." },
            { name: "Korean Beef Taco", price: 4.35, description: "Onions, scallions, cilantro and radishes on a corn tortilla." },
            { name: "Carnitas Taco", price: 3.85, description: "Onions, scallions, cilantro and radishes on a corn tortilla." },
            { name: "Baja Fish Taco", price: 4.60, description: "Onions, scallions, cilantro, cabbage, radishes, salsa verde and chipotle sauce on a corn tortilla." },
            { name: "Wild Mushroom Taco", price: 4.35, description: "Corn, mixed peppers, cilantro, scallions, and poblano sauce on corn tortilla." },
            { name: "Chicken Tinga Taco", price: 3.85, description: "Smoky shredded chicken breast, lightly spiced and garnished with cilantro, scallions, and radishes. Choose up to 3 sauces: Salsa Verde, Salsa Roja, Habanero." },
            { name: "Veggie Taco", price: 3.85, description: "Corn, mixed peppers, cilantro, scallions, and poblano sauce on corn tortilla." },
          
            // Burritos Menu Items
            { name: "Skirt Steak Burrito", price: 11.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Adobo Chicken Burrito", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Al Pastor Burrito", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, pineapple and pico de gallo." },
            { name: "Crispy Shrimp Burrito", price: 13.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Tofu Burrito", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Barbacoa Burrito", price: 11.00, description: "Lettuce, rice, beans, cheese, sour cream and pico de gallo." },
            { name: "Chorizo Burrito", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Korean Beef Burrito", price: 11.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Carnitas Burrito", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Baja Fish Burrito", price: 13.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Wild Mushroom Burrito", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Chicken Tinga Burrito", price: 10.00, description: "Smoky shredded chicken breast, light spicy, lettuce, rice, beans, cheese, sour cream and pico de gallo." },
            { name: "Veggie Burrito", price: 9.50, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Breakfast Burrito", price: 9.00, description: "Chorizo, egg, cheese, sour cream, and pico de gallo." },
          
            // Bowls Menu Items
            { name: "Skirt Steak Bowl", price: 11.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Adobo Chicken Bowl", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Al Pastor Bowl", price: 10.00, description: "Cheese, onions, pineapple, mixed peppers, with a side of sour cream and pico de gallo." },
            { name: "Crispy Shrimp Bowl", price: 13.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Chorizo Bowl", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Barbacoa Bowl", price: 11.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Baja Fish Bowl", price: 13.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Korean Beef Bowl", price: 11.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Carnitas Bowl", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." },
            { name: "Wild Mushroom Bowl", price: 10.00, description: "Cheese, onions, red and green peppers, with a side of sour cream and pico de gallo." },
            { name: "Chicken Tinga Bowl", price: 10.00, description: "Cheese, onions, red and green peppers, with a side of sour cream and pico de gallo." },
            { name: "Veggie Bowl", price: 9.50, description: "Cheese, onions, red and green peppers, with a side of sour cream and pico de gallo." },
            { name: "Tofu Bowl", price: 10.00, description: "Lettuce, rice, beans, cheese, sour cream, and pico de gallo." }
            // More items can be added here following the same structure.
          ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
  {
    id: 4,
    name: "Maman Joon Kitchen",
    cuisine: ["persian", "kabobs", "comfort food"],
    address: "4531 Wisconsin Ave NW, Washington, DC 20016",
    nearestUniversity: "American University",
    acceptsCampusCard: true,
    distance: "0.8 miles",
    rating: 4.2,
    menuItems: [
        { name: "Dolmeh", price: 5.50, description: "Stuffed veggie grape leaves" },
        { name: "Falafel", price: 6.24, description: "Chickpea patties with tahini sauce" },
        { name: "Hummus", price: 6.24, description: "Chickpeas, sesame paste, garlic, olive oil, lemon juice" },
        { name: "Kashk O Bademjan", price: 6.24, description: "Sauteed eggplant, onion, mint, kashk" },
        { name: "Must O Mooseer", price: 6.24, description: "Yogurt mixed with chopped Persian shallots" },
        { name: "Shirazi Salad", price: 5.50, description: "Diced cucumber, tomato, onion, mint, olive oil lemon juice" },
        { name: "Ash E Reshteh", price: 6.24, description: "Chopped herbs, beans, caramelized onions, garlic, noodles, mint, kashk" },
        { name: "Maman's Salad", price: 0, description: "Spring greens, lettuce, tomato, cucumber, kalamata olives, Dijon herb dressing" },
        { name: "Mediterranean Salad", price: 10.70, description: "Spring greens, lettuce, tomato, cucumber, parsley, onion, olives, feta cheese, virgin olive oil and lemon juice dressing" },
        { name: "Tabbouleh Salad", price: 6.24, description: "Chopped parsley, spring onion, tomato, cucumber, cracked wheat, virgin olive oil and lemon dressing" },
        { name: "Chicken Kabob Sandwich", price: 12.45, description: "Chunks of chicken breast" },
        { name: "Falafel Wrap", price: 10.99, description: "Chickpea patties, Hummus, lettuce, pickles, shirazi salad, tahini sauce" },
        { name: "Ground Chicken Kabob Sandwich", price: 12.45, description: "Ground chicken, grated onion, cilantro, seasoning" },
        { name: "Koobideh Kabob", price: 13.45, description: "Ground beef, grated onions" },
        { name: "Spicy Ground Chicken Kabob", price: 12.45, description: "Ground chicken, grated onion with seasoning" },
        { name: "Barg (Filet Mignon Kabob)", price: 21.83, description: "Farmed Persian kabob prepared with prime cut of beef" },
        { name: "Beef Chenjeh Kabob", price: 18.99, description: "Marinated tender chunks of prime beef" },
        { name: "Chicken Kabob", price: 15.99, description: "Chicken breast in a special marinade" },
        { name: "Fesenjan with basmati rice", price: 16.60, description: "Chicken, walnut, pomegranate sauce" },
        { name: "Gheymeh Bademjan with basmati rice", price: 15.60, description: "Eggplant, beef, split peas, sun dried lime" },
        { name: "Ghormeh Sabzi with basmati rice", price: 15.60, description: "Beef cubes, fresh chopped herbs, beans and sun dried lime" },
        { name: "Ground Chicken Kabob 2 Skewers", price: 15.99, description: "Ground chicken, grated onion, and cilantro" },
        { name: "Koobideh Kabob (2 Skewers)", price: 16.99, description: "Ground beef, grated onions" },
        { name: "Lamb Shank (Baghali Polo)", price: 18.71, description: "Slow cooked full lamb shank with broad bean, dill rice" },
        { name: "Salmon Kabob", price: 20.79, description: "Skinless Chunks of Salmon in a special house marinade" },
        { name: "Soltani", price: 26.00, description: "Barg and Koobideh combo" },
        { name: "Spicy Ground Chicken 2 Skewers", price: 15.99, description: "Ground chicken, grated onion with seasoning" }
       ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
  {
    id: 5,
    name: "Satay Club",
    cuisine: ["american", "appetizers", "comfort food"],
    address: "4654 Wisconsin Ave NW, Washington, DC 20016",
    nearestUniversity: "American University",   
    acceptsCampusCard: true,
    distance: "0.9 miles",
    rating: 4.2,
    menuItems: [
        { name: "CHICKEN SATAY (4)", price: 7.50, description: "Chicken skewers served with peanut sauce" },
        { name: "LAMB/BEEF/SHRIMP SATAY (4)", price: 8.50, description: "Lamb, beef, or shrimp skewers served with peanut sauce" },
        { name: "SATAY TOFU", price: 7.95, description: "Served with cucumbers, bean sprouts, and peanut sauce" },
        { name: "ROTI CANAI (2)", price: 6.95, description: "Indian pancakes served with curry sauce" },
        { name: "THAI LETTUCE WRAPS", price: 9.95, description: "Served with grilled chicken, assorted vegetables, and peanut sauce" },
        { name: "HOMEMADE BBQ SPARE RIBS (3)", price: 8.95, description: "BBQ ribs served with house sauce" },
        { name: "VEGETABLE SPRING ROLLS (3)", price: 4.50, description: "Crispy spring rolls filled with mixed vegetables" },
        { name: "VIETNAMESE SUMMER ROLLS (2)", price: 7.95, description: "Shrimp, vegetables, mango, and vermicelli noodles wrapped in fresh rice paper. Served with hoisin sauce" },
        { name: "FRIED CALAMARI", price: 9.95, description: "Fried calamari served with dipping sauce" },
        { name: "VIETNAMESE SPRING ROLLS (2)", price: 7.95, description: "Deep fried rolls with minced pork, fresh crabmeat, and cellophane noodles" },
        { name: "PORK DUMPLINGS (5)", price: 7.95, description: "Choice of steamed or pan-fried pork dumplings" },
        { name: "VEGETABLE DUMPLINGS (5)", price: 7.95, description: "Choice of steamed or pan-fried vegetable dumplings" },
        { name: "SHU MAI (6)", price: 6.95, description: "Shrimp dumplings. Choice of steamed or deep fried" },
        { name: "ROCK SHRIMP TEMPURA (6)", price: 9.95, description: "Coated with spicy mayo. Served with a house salad" },
        { name: "PEKING DUCK CREPE (2)", price: 9.95, description: "Stuffed with duck strips, ginger, scallions, and hoisin sauce" },
        { name: "CRAB RANGOON (5)", price: 7.95, description: "Crab and cream cheese wontons, fried to golden crispiness" },
        { name: "EDAMAME", price: 6.50, description: "Boiled soybeans with sea salt" },
        { name: "GREEN SALAD", price: 6.95, description: "Mixed greens with ginger dressing" },
        { name: "AVOCADO SALAD", price: 7.95, description: "Mixed greens, avocado, fried onion, sweet chili sauce, and ranch dressing" },
        { name: "GINGER SALAD", price: 7.50, description: "Fresh cabbage, carrots, pickled ginger, peanuts, and deep fried shallots with ginger dressing" },
        { name: "SPICY CRUNCHY SALMON SALAD", price: 8.50, description: "Raw salmon with spicy mayo and tempura flakes" },
        { name: "SEAWEED SALAD", price: 6.95, description: "Mixed seaweed with sesame oil and soy sauce" },
        { name: "MISO SOUP", price: 3.95, description: "Classic Japanese miso broth with tofu and seaweed" },
        { name: "HOT AND SOUR SOUP", price: 4.50, description: "Spicy and tangy soup with mushrooms, tofu, and bamboo shoots" },
        { name: "WONTON SOUP", price: 4.50, description: "Deep fried chicken wontons in a chicken broth" },
        { name: "TOM YUM SOUP", price: 4.95, description: "Spicy Thai soup with shrimp, mushrooms, and lemongrass" },
        { name: "LEMONGRASS COCONUT SOUP", price: 4.95, description: "Coconut-based soup with lemongrass and chicken" },
        { name: "NASI LEMAK", price: 16.95, description: "Coconut rice, sambal shrimp, fried egg, peanuts, indian chips, chicken satay, and fried chicken" },
        { name: "SAMBAL SHRIMP AND SQUID", price: 17.95, description: "Shrimp and squid stir fried with spicy sambal paste" },
        { name: "SALT AND PEPPER SHRIMP", price: 17.95, description: "Jumbo shrimp lightly battered and deep fried with spicy salt and garlic. Served with a salad mix" },
        { name: "RENDANG BEEF", price: 18.95, description: "Coconut beef stew served with slices of cucumber and Indian crackers" },
        { name: "MALAYSIAN RED CURRY", price: 14.95, description: "Choice of protein served with eggplant, string beans, fried tofu, carrots, and cabbage" },
        { name: "PEKING DUCK", price: 23.95, description: "Sliced roasted duck served with pancakes (4), scallions, and hoisin sauce" },
        { name: "GREEN CURRY", price: 16.95, description: "Choice of protein served with tomatoes, eggplant, string bean, fried tofu, and basil leaves" },
        { name: "THAI RED CURRY SHRIMP", price: 17.95, description: "Jumbo shrimp with basil leaves, eggplant, fried tofu, and string beans" },
        { name: "RED SNAPPER", price: 17.95, description: "Choice of ginger and scallion sauce or Thai spicy sauce" },
        { name: "SHREDDED PORK WITH HOT PEPPERS", price: 15.95, description: "Shredded pork stir fried with hot peppers" },
        { name: "CRISPY BEEF", price: 17.95, description: "Deep fried beef in a crispy batter with sweet and spicy sauce" },
        { name: "BLACK PEPPER STEAK", price: 18.95, description: "Beef steak stir fried with black pepper sauce" }
          ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
  {
    id: 6,
    name: "Tatte Bakery & Cafe",
    cuisine: ["american", "appetizers", "comfort food"],
    address: "13 Ridge Square, Washington, DC 20016",
    nearestUniversity: "American University",
    acceptsCampusCard: true,
    distance: "0.8 miles",
    rating: 4.2,
    menuItems: [
        { name: "House Breakfast Plate", price: 10.75, description: "Two eggs your style, Applewood-smoked bacon, and potato fritters with tomato jam and mint parmesan. Served with housemade sourdough. (660 cal, Contains: Milk, Egg, Wheat)" },
        { name: "Sausage Breakfast Sandwich", price: 8.50, description: "Housemade Sujuk-spiced beef sausage with an egg your style*, VT cheddar, fresh tomato, on a housemade challah roll (810 cal, Contains: Wheat, Egg, Milk)" },
        { name: "Smoked Salmon, Avocado, & Egg Sandwich", price: 12.75, description: "Smoked salmon, avocado, red onion, capers, alfalfa sprouts, and creamy scrambled eggs served on a housemade challah roll with green herbed dressing. (630 cal, Contains: Wheat, Milk, Egg, Soy, Fish)" },
        { name: "Breakfast Sandwich", price: 10.00, description: "Eggs your style, Vermont cheddar, and applewood smoked bacon on housemade sourdough. (870 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Croissant Breakfast Sandwich", price: 11.25, description: "Egg your style, Vermont cheddar, sliced tomato, avocado, and baby arugula on housemade croissant. (680 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Halloumi & Sunny-Side Breakfast Sandwich", price: 9.85, description: "Seared halloumi cheese, griddled tomatoes, and sautéed spinach with a sunny-side up egg on our house-made challah roll. (520 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Croque Monsieur", price: 12.85, description: "Housemade croissant, ham, Gruyere and Mornay sauce. (660 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Croque Madame", price: 13.85, description: "Housemade croissant, ham, Gruyere, egg your style, and Mornay sauce. (790 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Lamb Hash", price: 15.25, description: "Lamb cooked with warm spices sautéed with potatoes, sweet potatoes, carrots, pickled red cabbage, and topped with a poached egg and green dressing. Served with roasted garlic labneh, tomato salad, and housemade challah. (930 cal, Contains: Wheat, Milk, Egg, Soy)" },
        { name: "Egg in the Hole", price: 13.50, description: "Two fried eggs nestled in a housemade sesame Jerusalem bagel, served with chopped salad. (680 cal, Contains: Wheat, Milk, Egg, Sesame)" },
        { name: "Egg in the Hole with Ham & Cheese", price: 15.00, description: "Two fried eggs, ham, and Vermont cheddar cheese nestled in a sesame Jerusalem bagel, served with chopped salad. (860 cal, Contains: Wheat, Milk, Egg, Sesame)" },
        { name: "Prosciutto & Parmesan Scrambled Egg Plate", price: 10.75, description: "Two eggs soft scrambled served with prosciutto, Parmesan, and toasted housemade sourdough. (640 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Tomato & Goat Cheese Scrambled Egg Plate", price: 10.75, description: "Two eggs soft scrambled served with ricotta goat cheese mousse and sun-dried cherry tomatoes marinated in garlic and olive oil served with toasted housemade sourdough. You can add on sautéed spinach. (690 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Warm Oatmeal & Fruit", price: 7.25, description: "Warm oatmeal topped with fresh blueberries, orange blossom honey-soaked dried apricots and golden raisins, black sesame, sunflower and pumpkin seeds with a ginger date syrup. (Contains: Sesame)" },
        { name: "Muesli", price: 7.25, description: "Whipped Greek yogurt topped with housemade granola, raspberries, blueberries, blackberries, pear, apple, honey, and black sesame. (670 / 980 cal, Contains: Milk, Sesame, Tree Nut - Almond, Cashew)" },
        { name: "Bread & Butter", price: 6.00, description: "Toasted housemade bread served with butter and housemade jam. (710 cal, Contains: Wheat, Milk, Egg, Sesame)" },
        { name: "Roasted Salmon Sandwich", price: 16.50, description: "Roasted salmon served with herbed mayo, arugula, red onion, pickled red cabbage, sumac, and tomato on a housemade challah roll. (1010 cal, Contains: Wheat, Egg, Soy, Fish)" },
        { name: "BLAT", price: 12.75, description: "Applewood smoked bacon, baby lettuce, avocado, sriracha mayonnaise, and tomato-onion relish on housemade challah. (870 cal, Contains: Wheat, Egg, Soy)" },
        { name: "Turkey BLAT", price: 13.00, description: "Turkey, applewood smoked bacon, baby lettuce, avocado, sriracha mayonnaise, and tomato-onion relish on housemade multigrain. (840 cal, Contains: Wheat, Egg, Soy)" },
        { name: "Chicken Pita", price: 12.75, description: "Roasted chicken breast with a chopped salad of tomatoes, cucumber, red onion, parsley, baby lettuce, and green herb dressing in a pita. (500 cal, Contains: Wheat, Milk, Egg, Soy)" },
        { name: "Lamb Kebab Pita", price: 14.00, description: "Lamb kebab with a chopped salad of tomatoes, cucumber, red onion, parsley served with dill labneh in a warm pita. (710 cal, Contains: Wheat, Milk)" },
        { name: "Chicken Salad Sandwich", price: 12.75, description: "Housemade herbed chicken salad with raisins, marinated cucumbers, and baby lettuce, served with a green herb dressing on housemade multigrain. (860 cal, Contains: Wheat, Milk, Egg, Soy)" },
        { name: "Turkey Avocado Sandwich", price: 12.75, description: "Turkey, avocado, baby lettuce, cucumbers, with a green herb dressing on housemade challah. (730 cal, Contains: Wheat, Milk, Egg, Soy)" },
        { name: "Broccolini & Squash Hummus Pita", price: 12.25, description: "Roasted broccolini, butternut squash hummus, roasted mushrooms, and pickled cabbage with a green tahini sauce. (Contains: Wheat, Sesame)" },
        { name: "Fresh Mozzarella Sandwich", price: 12.25, description: "Fresh mozzarella, sliced tomatoes, baby arugula, and basil pine nut pesto on housemade ciabatta. (940 cal, Contains: Wheat, Milk, Tree Nut - Pine)" },
        { name: "Roasted Cauliflower Sandwich", price: 12.25, description: "Roasted cauliflower, pine nuts, spiced labneh, golden raisins, chilies, cilantro, and capers on pita. (520 cal, Contains: Wheat, Milk, Tree Nut - Pine)" },
        { name: "Tuna Sandwich", price: 12.75, description: "Olive oil packed tuna salad, hardboiled egg, shaved red onion, yogurt and dill served on housemade challah. (870 cal, Contains: Wheat, Milk, Egg, Fish)" },
        { name: "Prosciutto & Fig Panini", price: 13.25, description: "Fig jam, brie, fontina cheese, prosciutto and sliced Bosc pear on housemade ciabatta. (990 cal, Contains: Wheat, Milk)" },
        { name: "Short Rib Grilled Cheese Sandwich", price: 13.25, description: "Braised short rib, beet-horseradish relish and cheddar on housemade challah. (640 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Grilled Cheese", price: 11.00, description: "Fontina, VT Cheddar, parmesan, sundried tomato, roasted garlic, capers, dijon mustard, parsley and thyme spread on a housemade sourdough. (850 cal, Contains: Wheat, Milk)" },
        { name: "Kids Sandwich", price: 6.00, description: "A classic Tatte sandwich. Toasted challah bread with sliced cheddar cheese. (430 cal, Contains: Wheat, Milk, Egg)" },
        { name: "Smoked Salmon and Avocado Tartine", price: 14.00, description: "Smoked Salmon, avocado, Campari tomatoes, red onion, capers, and dill tossed with olive oil served over toasted housemade sourdough with green herbed dressing. (740 cal, Contains: Wheat, Milk, Egg, Soy, Fish)" },
        { name: "Avocado Tartine", price: 13.00, description: "Avocado, baby arugula, dill, and radish with poached eggs on sourdough. (670 cal, Contains: Wheat, Egg)" }
      
    ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
  {
    id: 7,
    name: "Pizzeria Paradiso",
    cuisine: ["pizza", "italian"],
    address: "4850 Massachusetts Ave NW, Washington, DC 20016",
    nearestUniversity: "American University",
    acceptsCampusCard: true,
    distance: "0.2 miles",
    rating: 4.2,
    menuItems: [
        { name: "Margherita", price: 18.00, description: "Paradiso Tomato Sauce, Basil, Buffalo Mozzarella", largePrice: 25.00 },
        { name: "Macellaio", price: 18.00, description: "Paradiso Tomato Sauce, Pepperoni, Mozzarella, Pork Sausage, Red Onions", largePrice: 25.00 },
        { name: "Bosco", price: 17.00, description: "Paradiso Tomato Sauce, Spinach, Mozzarella, Mushrooms, Red Onions", largePrice: 24.00 },
        { name: "Quattro Formaggi", price: 17.00, description: "Gorgonzola, Pecorino, Grana Padano, Mozzarella, Minced Garlic, Parsley", largePrice: 24.00 },
        { name: "Atomica", price: 17.00, description: "Paradiso Tomato Sauce, Salami, Kalamata Olives, Hot Pepper Flakes, Mozzarella", largePrice: 24.00 },
        { name: "Genovese", price: 16.00, description: "Pesto, Potato, Grana Padano", largePrice: 23.00 },
        { name: "Napoletana", price: 17.00, description: "Paradiso Tomato Sauce, Basil, Anchovy, Capers, Mozzarella", largePrice: 24.00 },
        { name: "Bottarga", price: 18.00, description: "Paradiso Tomato Sauce, Minced Garlic, Parsley, Grana Padano, Egg, Bottarga", largePrice: 25.00 },
        { name: "Siciliana", price: 17.00, description: "Paradiso Tomato Sauce, Zucchini, Eggplant, Caper, Minced Garlic, Oregano, Mozzarella, Pecorino, Red Sweet Pepper, Red Onion", largePrice: 24.00 },
        { name: "Paesana", price: 18.00, description: "Spicy Garlic Pesto, Paradiso Chicken Sausage, Sweet Red Peppers, Roasted Escarole, Broccoli Rabe, Mozzarella, Ricotta", largePrice: 25.00 },
        { name: "Paradiso", price: 15.00, description: "Paradiso Tomato Sauce or Birreria Tomato Sauce, Mozzarella", largePrice: 22.00 },
        { name: "Miniera", price: 18.00, description: "Paradiso Tomato Sauce or Birreria Tomato Sauce, Mozzarella, Three Toppings of Your Choice", largePrice: 25.00 },
        { name: "Di Mare", price: 18.00, description: "Spicy Garlic Pesto, Shrimp, Spinach, Red Onions, Grana Padano", largePrice: 25.00 }
    ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
  {
    id: 8,
    name: "Saladworks",
    cuisine: ["salad", "american"],
    address: "320 Florida Avenue NE Washington 20002",
    nearestUniversity: "Howard University",
    acceptsCampusCard: true,
    distance: "1.8 miles",
    rating: 4.2,
    menuItems: [
        { name: "A Salad Creation of Your Own", price: 12.29, description: "Be Original by creating your own Salad. Start by picking your base, then add your favorite toppings and dressing." },
        { name: "Grilled Chicken Caesar Salad", price: 11.99, description: "Our Grilled Chicken Caesar comes recommended with a base of Romaine/Iceberg Blend, topped with grilled chicken, parmesan cheese, and croutons." },
        { name: "Smoky BBQ Chicken Salad", price: 11.99, description: "This Chef-inspired Signature starts with a recommended base of Romaine/Iceberg Blend, topped with BBQ chicken, corn, black beans, and tortilla strips." },
        { name: "Avocado Cobb Salad", price: 11.99, description: "Fresh Avocado enhances this timeless classic! Start with the recommended Romaine/Iceberg Blend, topped with grilled chicken, bacon, egg, and blue cheese." },
        { name: "Southwest Chipotle Ranch Salad", price: 11.99, description: "Our Chef-inspired regional favorite starts with a recommended base of Romaine/Iceberg Blend, topped with spicy chicken, corn, black beans, and tortilla strips." },
        { name: "Bently Salad", price: 11.99, description: "Our Chef recommends a base of our Romaine/Iceberg Blend. It is served with grilled chicken, cranberries, apple chips, and walnuts." },
        { name: "Asian Chicken Salad", price: 11.99, description: "Our Chef recommends a base of our Super Greens Blend. It is served with grilled chicken, mandarin oranges, crispy noodles, and sesame ginger dressing." },
        { name: "Sophie's Salad", price: 11.99, description: "This Napa-inspired Signature starts with a recommended base of our Spring Mix, topped with grilled chicken, goat cheese, cranberries, and candied pecans." },
        { name: "Grilled Chicken Mediterranean Salad", price: 11.99, description: "This Mediterranean-inspired Signature features a recommended base of our Spring Mix, topped with grilled chicken, feta cheese, olives, and grape tomatoes." },
        { name: "Buffalo Bleu Salad", price: 11.99, description: "Our Chef recommends a base of our Romaine/Iceberg Blend. It's served with buffalo chicken, blue cheese crumbles, tomatoes, and celery." },
        { name: "Farmers Market Salad", price: 11.99, description: "Our Chef-inspired Farmers Market features a recommended base of our Super Greens Blend, topped with seasonal roasted vegetables and balsamic vinaigrette." },
        { name: "Roasted Turkey Club Salad", price: 11.99, description: "Our Roasted Turkey Club starts with a recommended base of Romaine/Iceberg Blend, topped with turkey, bacon, cheddar cheese, and tomatoes." },
        { name: "Classic Greek Salad", price: 11.99, description: "Our Classic Greek Salad starts with a recommended base of Romaine/Iceberg Blend, topped with feta cheese, kalamata olives, red onions, and grape tomatoes." },
        { name: "Turkey 'n Cheddar (Sandwich)", price: 11.99, description: "Turkey medallions, spring mix, cheddar cheese, sliced tomatoes, on rustic white, honey mustard" },
        { name: "Turkey Bacon 'n Ranch (Sandwich)", price: 11.99, description: "Roasted turkey, smoky bacon, sliced tomato, spring mix, cheddar cheese, on hearty wheatberry, ranch" },
        { name: "Cranberry 'n Pecan Chicken Salad (Sandwich)", price: 11.99, description: "Housemade chicken salad made with honey roasted pecans, dried cranberries, chopped celery, spring mix, on hearty wheatberry" },
        { name: "Avocado BLT (Sandwich)", price: 11.99, description: "Smoky bacon, sliced tomato, spring mix, fresh avocado, on rustic white, green goddess" }  
    ],
    delivery: {
      doordash: true,
      ubereats: true,
      grubhub: true,
      inhouse: false
    }
  },
];

export const universities = [
    "All Universities",
    "Georgetown University",
    "American University",
    "Howard University"
];
export const cuisineTypes = [
    "All Cuisines",
    "american",
    "appetizers", 
    "comfort food",
    "pizza",
    "italian",
    "mexican",
    "tacos",
    "persian",
    "kabobs"
];